apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db2
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: db2
    spec:
      schedulerName: stork
      containers:
      - name: db2express-c
        command: ["/entrypoint.sh","db2start"]
        image: ibmcom/db2express-c:10.5.0.5-3.10.0
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 50000
        env:
        - name: DB2INST1_PASSWORD
          value: somepasswd!
        - name: LICENSE
          value: accept
        volumeMounts:
        - mountPath: /home/db2inst1/db2-data/
          name: db2data
      securityContext:
        fsGroup: 1001
      volumes:
      - name: db2data
        persistentVolumeClaim:
          claimName: px-db2-pvc