apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db2
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: db2
    spec:
      schedulerName: stork
      containers:
      - name: db2
        image: store/ibmcorp/db2_developer_c:11.1.3.3b-x86_64
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 50000
        env:
        - name: DB2INST1_PASSWORD
          value: "somepasswd!"
        - name: LICENSE
          value: "accept"
        - name: TO_CREATE_SAMPLEDB
          value: "true"
        - name: DB2INSTANCE
          value: "db2inst1"
        volumeMounts:
        - mountPath: /database
          name: db2data
        securityContext:
          privileged: true
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: db2data
        persistentVolumeClaim:
          claimName: px-db2-pvc