kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: px-repl3-db2-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   block_size: "512b"
   io_profile: "db"
allowVolumeExpansion: true